// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock_hq.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace StockHq {
  public static partial class StockHQService
  {
    static readonly string __ServiceName = "stock_hq.StockHQService";

    static readonly grpc::Marshaller<global::stock_min> __Marshaller_stock_min = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::stock_min.Parser.ParseFrom);

    static readonly grpc::Method<global::stock_min, global::stock_min> __Method_ListFeatures = new grpc::Method<global::stock_min, global::stock_min>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ListFeatures",
        __Marshaller_stock_min,
        __Marshaller_stock_min);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::StockHq.StockHqReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of StockHQService</summary>
    public abstract partial class StockHQServiceBase
    {
      /// <summary>
      ///rpc RouteChat (stream long) returns (stream long_hq);
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task ListFeatures(global::stock_min request, grpc::IServerStreamWriter<global::stock_min> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for StockHQService</summary>
    public partial class StockHQServiceClient : grpc::ClientBase<StockHQServiceClient>
    {
      /// <summary>Creates a new client for StockHQService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StockHQServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for StockHQService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StockHQServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StockHQServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StockHQServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///rpc RouteChat (stream long) returns (stream long_hq);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::stock_min> ListFeatures(global::stock_min request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ListFeatures(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///rpc RouteChat (stream long) returns (stream long_hq);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::stock_min> ListFeatures(global::stock_min request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ListFeatures, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StockHQServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StockHQServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StockHQServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListFeatures, serviceImpl.ListFeatures).Build();
    }

  }
}
#endregion
