# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_hq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stock_min_pb2 as stock__min__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stock_hq.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0estock_hq.proto\x1a\x0fstock_min.proto2:\n\x0eStockHQService\x12(\n\x0cListFeatures\x12\n.stock_min\x1a\n.stock_min0\x01\x62\x06proto3')
  ,
  dependencies=[stock__min__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STOCKHQSERVICE = _descriptor.ServiceDescriptor(
  name='StockHQService',
  full_name='StockHQService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=35,
  serialized_end=93,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListFeatures',
    full_name='StockHQService.ListFeatures',
    index=0,
    containing_service=None,
    input_type=stock__min__pb2._STOCK_MIN,
    output_type=stock__min__pb2._STOCK_MIN,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STOCKHQSERVICE)

DESCRIPTOR.services_by_name['StockHQService'] = _STOCKHQSERVICE

# @@protoc_insertion_point(module_scope)
